version: 2.{build}
image: Visual Studio 2013
configuration: Release
platform:
- x86
- x64
build:
  project: xAnalyzer.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - yunietps@yahoo.com
  subject: AppVeyor Build
  message: A new build has been created!
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
